oauth:
  user:
    client-id: ${github_client_id}
    client-secret: ${github_secret_key}
    redirect-url: http://localhost:8080/login/oauth

  provider:
    token-url: https://github.com/login/oauth/access_token
    user-info-url: https://api.github.com/user

jwt:
  secret-key: ${jwt_secret}
  expire-length: ${jwt_expire_length}
