spring:

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
    open-in-view: false

  #  추가해야 data.sql실행
  sql:
    init:
      mode: always

  config:
    import: application-localproperty.yml

logging.level:
  org.hibernate.SQL: debug
  org.springframework.transaction.interceptor: trace
#  org.hibernate.type: trace
  org.hibernate.type.BasicTypeRegistry: WARN
