spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true

  sql:
    init:
      data-locations:
        - classpath:db/data.sql
      mode: always
      encoding: UTF-8

logging:
  level:
    org.hibernate.SQL: debug
