spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/airbnb?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: elql1004

  sql:
    init:
      data-locations: classpath:data.sql
      mode: always

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
    defer-datasource-initialization: true


logging:
  level.com.codesquad.airbnb: debug


