spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://0.0.0.0:3306/airbnb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  sql:
    init:
      schema-locations: classpath*:sql/schema.sql
      data-locations: classpath*:sql/data.sql
      mode: never

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

  logging.level:
    org.hibernate.SQL: debug
