spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        # 포인트 사용을 위해서 반드시 추가해야함
        dialect: team15.airbnb.category.infrastructure.AirbnbMySqlDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_DATABASE_USERNAME}
    url: ${MYSQL_DATABASE_URL}
    password: ${MYSQL_DATABASE_PASSWORD}
logging:
  level:
    team15:
      airbnb: info
