spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        # 포인트 사용을 위해서 반드시 추가해야함
#        dialect: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
        dialect: team15.airbnb.category.infrastructure.AirbnbMySqlDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/airbnb?&characterEncoding=UTF-8&serverTimeZone=Asia/Seoul
    password: team-15

logging:
  level:
    org.hibernate.SQL: debug
    team15:
      airbnb: debug

